export const TOGGLE_DEVICE = 'TOGGLE_DEVICE'

export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR'

export const EXPAND_MENU = 'EXPAND_MENU'

export const SWITCH_EFFECT = 'SWITCH_EFFECT'

export const AUTHENTICATE_REQUEST = 'AUTHENTICATE_REQUEST'

export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS'

export const AUTHENTICATE_FAILURE = 'AUTHENTICATE_FAILURE'

export const GET_BANNER_REQUEST = 'GET_BANNER_REQUEST'

export const GET_BANNER_SUCCESS = 'GET_BANNER_SUCCESS'

export const GET_BANNER_FAILURE = 'GET_BANNER_FAILURE'
